fiberstat: add missing stdint.h header
    fiberstat.c:427:5: error: unknown type name 'uint8_t'
         uint8_t  sfp_phandle[PHANDLE_SIZE_BYTES];
         ^